{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "objectio.grafana.fullname" . }}
  labels:
    {{- include "objectio.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "objectio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
