apiVersion: v1
kind: Service
metadata:
  name: {{ include "objectio.meta.fullname" . }}
  labels:
    {{- include "objectio.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.meta.service.port }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.meta.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "objectio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: meta
