[package]
name = "objectio-gateway"
description = "S3 API Gateway for ObjectIO"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "objectio-gateway"
path = "src/main.rs"

[dependencies]
objectio-common = { workspace = true }
objectio-erasure = { workspace = true }
objectio-s3 = { workspace = true }
objectio-client = { workspace = true }
objectio-proto = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tonic = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
quick-xml = { workspace = true }
bytes = { workspace = true }
http-body-util = "0.1"
md5 = "0.7"
crc32c = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
objectio-auth = { workspace = true }
objectio-iceberg = { workspace = true }
http = "1.2"
chrono = "0.4"
ring = { workspace = true }
base64 = { workspace = true }
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
regex = "1"
urlencoding = "2"
